<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NuGetAudit>false</NuGetAudit>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ANLAbel.Core\ANLAbel.Core.csproj" />
    <ProjectReference Include="..\ANLAbel.Barcode\ANLAbel.Barcode.csproj" />
    <ProjectReference Include="..\ANLAbel.Data\ANLAbel.Data.csproj" />
    <ProjectReference Include="..\ANLAbel.Project\ANLAbel.Project.csproj" />
    <ProjectReference Include="..\ANLAbel.Printing\ANLAbel.Printing.csproj" />
    <ProjectReference Include="..\ANLAbel.App\ANLAbel.App.csproj" />
  </ItemGroup>

</Project>
