<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsTestProject>true</IsTestProject>
    <NuGetAudit>false</NuGetAudit>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
    <PackageReference Include="Xunit.StaFact" Version="1.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ANLAbel.Core\ANLAbel.Core.csproj" />
    <ProjectReference Include="..\ANLAbel.Barcode\ANLAbel.Barcode.csproj" />
    <ProjectReference Include="..\ANLAbel.Data\ANLAbel.Data.csproj" />
    <ProjectReference Include="..\ANLAbel.Project\ANLAbel.Project.csproj" />
    <ProjectReference Include="..\ANLAbel.Printing\ANLAbel.Printing.csproj" />
    <ProjectReference Include="..\ANLAbel.App\ANLAbel.App.csproj" />
  </ItemGroup>

</Project>
